### ISSUE TITLE
Move over basic-taq directory from  BIDS-collaborative

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-taq#1]
File is at https://github.com/BIDS-collaborative/dlab-finance/blob/master/basic-taq/raw_taq.py

Once we have that, remove from the BIDS-collaborative repo.

**Comment by davclark** [comment]
cc @yangraymond

**Comment by davclark** [comment]
You can get information on how to structure a python package at the [Python Packaging Guide](https://packaging.python.org/en/latest/).

**Comment by davclark** [comment]
If you get stuck, drop back into the [dlab-finance room](https://gitter.im/BIDS-collaborative/dlab-finance).

**Comment by juanshishido** [comment]
Done and done.

**Comment by davclark** [comment]
I should've been a bit more clear. This is meant to be a python package. So, it should have library code, tests, and data necessary to run the tests. That directory should mostly stay in dlab-finance.

I forgot to mention it here, but in talking to @yangraymond, we agreed that simply `taq` would be a nice name for the module itself.

Also see above for information on how to structure a python package.

**Comment by juanshishido** [comment]
No worries. I didn't see the other comments. I'll restructure.

**Comment by davclark** [comment]
The stuff that should be left in that `dlab-berkeley/raw_taq` directory could also get updated to use the new module. That's a great first test. But you can treat that as a separate issue (which should be filed in that repo).
