### ISSUE TITLE
`import taq` should populate the taq namespace with the basic classes

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-taq#3]
Once this is working, notebooks and things should be updated in dlab-finance.

**Comment by davclark** [comment]
See #1 for history.

**Comment by juanshishido** [comment]
Edited raw_taw.py: removed "from" with 80e89a3ea30ccffe661537de72b70feea01bfcf1.

Added __init__.py, importing BytesSpec and TAQ2Chunks with 46b7c854c4f85c056ff98791156916a75f6548e1
