### ISSUE TITLE
Create a basic test to understand pytest

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-taq#7]
Something like:

1. Create f(x) = x + 2
2. Test that f(x) = x + 3
3. See that test fails
4. Fix the failing test

Feel free to do that in the repo... it'll help us move forward in having a test directory in the right place. Let's start with pytest.

**Comment by juanshishido** [comment]
@yangraymond how is this task progressing? If you need anything, I'd be more than happy help.

**Comment by davclark** [comment]
Note - I put some basic stuff in the repo, but I'd promised @yangraymond a bit more... so don't feel like you "dropped the ball" if you're not there yet. But do reach out!

**Comment by yangraymond** [comment]
This has been done. Jie and Juan helped me understand what sort of things need to be tested (e.g. ensure number of rows in original zip file must match number of rows in processed HDF5). I think it seems appropriate to get started in iPython (I've downloaded 20140206.zip from Box into my local directory) and I'll try to replicate some of the things Jie has done in his "Checking a chunk.ipynb" to better understand the Taq2Chunks class.
